feat: add elasticsearch component
instill-ai/component pull request #211
Opened 2024-07-11 21:37 UTC by zidanehakim

Because

- We need to integrate Elasticsearch into our data pipeline.
- This will allow us to cover data movement user stories

This commit

- Allow client to connect to their Elasticsearch database through VDP
- Auth using passwordless API Key and cloud ID through elasticsearch go sdk
- Create execution function to handle basic operations (update, index(insert), delete, search)

2024-07-26 16:39 UTC, chuang8511 commented
memo
https://github.com/ollama/ollama/issues/849 related issue.

2024-08-08 03:39 UTC, donch1989 requested changes

2024-08-08 03:39 UTC, donch1989 commented on data/elasticsearch/v0/tasks.go
> +	_, err = esClient(indexName, bytes.NewReader(dataJSON), func(r *esapi.IndexRequest) {
```suggestion
	resp, err := esClient(indexName, bytes.NewReader(dataJSON), func(r *esapi.IndexRequest) {
```
We need to check the error in the `resp` as well. The `err` can not catch all errors.

2024-08-08 03:39 UTC, donch1989 commented on data/elasticsearch/v0/config/tasks.json
> +        "mappings"
Mapping should be optional.

2024-08-08 03:39 UTC, donch1989 commented on data/elasticsearch/v0/config/tasks.json
> +        "update"
```suggestion
        "update-data"
```

2024-08-08 09:23 UTC, merged