feat(artifact): add artifact componen
instill-ai/component pull request #268
Opened 2024-08-01 19:04 UTC by chuang8511

Because

- we want vdp able to access to artifact to enrich the capability of the products in instill AI

This commit

- add the schema of artifact component

2024-08-01 19:09 UTC, chuang8511 commented
Hi @donch1989 ,
According to the new flow, you can review schema first.

2024-08-05 07:04 UTC, donch1989 requested changes

2024-08-05 09:35 UTC, chuang8511 commented on data/artifact/v0/config/setup.json
> +    "namespace": {
@donch1989 
I think namespace is more like "account name" such as login information, so I put it in setup section.
Will it be better to put them in tasks section?

2024-08-05 18:26 UTC, chuang8511 commented
todo: take out api token

2024-08-06 08:09 UTC, chuang8511 commented
@donch1989 
I have
- moved namespace to tasks
- take out api token

2024-08-07 02:00 UTC, donch1989 approved these changes
LGTM

2024-08-07 02:02 UTC, merged