feat(artifact): add retrieve messages and write message tasks
instill-ai/component pull request #290
Opened 2024-08-19 17:07 UTC by chuang8511

Because

- we want catalog to able to have the memory system to achieve AI assistant

This commit

- implement the tasks about the messages

2024-08-19 17:08 UTC, chuang8511 commented
There are 2 things that we have to check and do
1. e2e test
2. test code

2024-08-20 01:14 UTC, donch1989 requested changes

2024-08-20 01:14 UTC, donch1989 commented on data/artifact/v0/config/tasks.json
> +        "next-page-token": {
We don't have page-token in input, there is no need to return next-page-token.

2024-08-20 01:14 UTC, donch1989 commented on data/artifact/v0/config/tasks.json
> +              "catalog-id": {
I think all messages in the array should share the same `catalog-id` and `conversation-id`, also matching the user's input. There's no need to return them in the output again.

2024-08-20 15:20 UTC, chuang8511 commented
Convert it to draft because we will modify it after standardised AI task.

2024-09-10 22:14 UTC, chuang8511 commented on data/artifact/v0/chat_operation.go
> +	_, err = artifactClient.CreateConversation(ctx, &artifactPB.CreateConversationRequest{
please use ListConversations.
If there is no Conversation, call CreateConversation.

2024-09-20 11:08 UTC, closed without merging